* Algorithms
This repository contains the practices of the course of Algorithms of the University of A Coruña in the degree of computer engineering second course of 2022/2023.

** Contenido de cada práctica
There are four practices with their content separated in individual folders, each of them has a pdf with the exercises to complete, a .c file with the code and a report with the answer, explanation and analysis.

*** [[https://github.com/antonlnz/Algoritmos/tree/main/P1][Práctica 1]]
It consists in comparing the performance of three algorithms that compute the fibonacci sequence up to a given n. The correct implementation in C of both algorithms and empirical verification of the theoretical complexity.
Grade: 9/10

*** [[https://github.com/antonlnz/Algoritmos/tree/main/P2][Práctica 2]]
It consists of comparing the performance of two sorting algorithms (*insertion* and *Quicksort*). The correct C implementation of both algorithms and empirical verification of the theoretical complexity. In this case QuickSort will be implemented with pivot selection by median of three and we must compare its performance with three different thresholds 1,10 and 100.
Grade: 7.5/10

*** [[https://github.com/antonlnz/Algoritmos/tree/main/P3][Práctica 3]]
It consists of calculating the empirical complexity of the *insert* and *search* functions in binary search trees. The correct C implementation of both algorithms and empirical verification of the theoretical complexity.
Grade: 3.5/10

*** [[https://github.com/antonlnz/Algoritmos/tree/main/P4][Práctica 4]]
It consists of implementing the sorting algorithm by monticules and making the empirical verification of the theoretical complexity.
Grade: 9.5
